apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-ec2nodeclass
      taints: []
      startupTaints: []
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3", "t3a", "t2", "c5a", "c6a"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium", "small", "micro"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["ap-northeast-1a", "ap-bortheast-1b", "ap-northeast-1c"]
  limits:
    cpu: "50"
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
    # Add budgets to control disruption rate
    budgets:
      - nodes: "100%"
        reasons:
          - "Drifted"
          - "Underutilized"
          - "Empty"
